services:

  usuariosapp:
    build:
      context: .
      dockerfile: UsuariosApp.API/Dockerfile
    container_name: usuariosapp_api
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
    restart: always
    networks:
      - usuariosapp_network
    environment:
      - ConnectionStrings__DataContext=Data Source=sqlserver,1433;Initial Catalog=master;User ID=sa;Password=Coti@2025;Encrypt=False;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usuariosapp_sqlserver
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Coti@2025
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - usuariosapp_network

volumes:
  sqlserver_data:

networks:
  usuariosapp_network:
    driver: bridge
